# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Willkommen bei TheRealJonas!
email: public.jbernard@web.de
description: >-
  Ich bin zwar eigentlich klein und unwichtig, befasse mich aber mit umso
  wichtigeren Themen. Aus meiner Sicht wichtig. Egal, ob es viele lesen,
  oder wenige.
url: "therealjonas.github.io"
twitter_username: TheRealJonas256
github_username: TheRealJonas
instagram_username: jonas.bern
pinterest_username: therealjonas256
timezone: Europe/Berlin
lang: de

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-include-cache


show-excerpts: "true"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comment: true
      comments: true
      title: "[Blogeintrag ohne Titel]"
      description: "Dieser Post hat keine Beschreibung."

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
