# Technichal stuff
url: https://jonasbernard.de
timezone: Europe/Berlin
lang: de

# Website title and other metadata
title: Jonas Bernard
email: public.jbernard@web.de
description: >-
  Eine Webseite, um meine Projekte zu präsentieren.

# Social information
github_username: JonasBernard

# Themeing
# theme: jekyll-theme-chirpy
# theme: jekyll-text-theme
remote_theme: kitian616/jekyll-TeXt-theme
paginate: 6

# Settigns specifically for TeXt Theme
toc:
  selectors: "h1,h2,h3"
text_skin: "dark"
highlight_theme: "tomorrow-night"
author:
  email: public.jbernard@web.de
  github: JonasBernard
  telegram: JonasBernard

excerpt_separator: <!--more-->

mathjax: true
mathjax_autoNumber:  true

highlighter : rouge
markdown: kramdown

comments:
  provider: "custom"

collections:
  apps:
    output: true

show_downloads: false

# Additional Content
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

show-excerpts: "true"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "page"
      author: Jonas Bernard
      comment: false
      license: false
      show_edit_on_github: false
      show_subscribe: true
      pageview: false
      aside:
        toc: false
      title: "[Artikel ohne Titel]"
      description: "Dieser Post hat keine Beschreibung."

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor
